language: rust
os:
  - linux
  - osx
  - windows
rust:
#  - stable
#  - beta
  - nightly
matrix:
  include:
    # Builds that are executed for every PR
    - os: osx # run base tests on both platforms
    - os: linux
    - os: windows
#  allow_failures:
#    - rust: nightly
