[package]
name = "rlinks"
version = "0.5.6"
authors = ["Jose Luis Ricon <jose@ricon.xyz>"]
edition = "2018"
license ="GPL-3.0-or-later"
repository="https://github.com/jlricon/rlinks"
categories=["web-programming::http-client"]
readme="README.md"
description="Rusty Links (rlinks) finds dead links in your website"
keywords=["links","url","async","check"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[badges.maintenance]
status = "actively-developed"
[dependencies]
colored="1.8"
clap="2"
select="0.4"
isahc="0.7"
url="2"
tokio="0.2.0-alpha.4"
http="0.1"
futures-preview = { version = "=0.3.0-alpha.18", features = ["async-await","nightly"] }
indicatif="0.11"
log = "0.4.8"
env_logger = "0.6.2"
[profile.dev]
debug-assertions=true
[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions=false
