[package]
name = "rlinks"
version = "0.5.0"
authors = ["Jose Luis Ricon <jose@ricon.xyz>"]
edition = "2018"
license ="GPL-3.0-or-later"
repository="https://github.com/jlricon/rlinks"
readme="README.md"
description="Rusty Links (rlinks) finds dead links in your website"
keywords=["links","url","blog","www"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored="1.8"
clap="2"
select="0.4"
isahc="0.7"
url="2"
tokio="0.2.0-alpha.4"
http="0.1"
futures-preview="0.3.0-alpha.18"
[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1