[package]
name = "rlinks"
version = "0.1.0"
authors = ["Jose Luis Ricon <jose@ricon.xyz>"]
edition = "2018"
license ="GPL"
repository="https://github.com/jlricon/rlinks"
description="Rusty Links (rlinks) finds dead links in your website (WIP)"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9"
tokio="0.1"
futures="0.1"
colored="1.8"
